### PR TITLE
[FLIN-136] Experimentation: patterns for aggregation

### PR DESCRIPTION
**Pull request by PolimiGiovanniArriciati**
---
name: Pull Request
about: Create a pull request to contribute to the project
assignee: 'Giovanni Arriciati'
---

## Describe your changes
I did some experimentation and put everything under [/docs/aggregation_experimentation](https://github.com/FlinkFood/FlinkFood/tree/featurea/FLIN-136-patterns-for-aggregation-and-storage-on-MongoDB/docs/aggregation_experimentation)

Full documentation can be found [here](https://docs.google.com/document/d/1wxCYG6w6nJVDsFXKLeSPREIqDegXsupX1SYRR2fyJKM/edit)

## Checklist before requesting a review
- [] I have performed a self-review of my code
- [X] I have updated/created the corresponding documentation

### CODE REVIEW

**Comment by MarcosPetrucci** [comment]
Could you explain this better?

Why should we have experimentation files in the Develop?

**Comment by VegSja** [comment]
Is this still active?

**Comment by PolimiGiovanniArriciati** [comment]
> Is this still active?

Yes, needs to be merged

**Comment by VegSja** [comment]
Could the merge conflicts be solved before I review this?

**Comment by PolimiGiovanniArriciati** [comment]
I'll try

**Pull request closed without merging**
