### PR TITLE
[FLIN-101] Complete Dish View

### PR DESCRIPTION
**Pull request by lucamozzz**
## Describe your changes
Using the new aggregation startegy brought up by Niccolò I was able to aggregate data in order to obtain the complete Dish View as requested by the customer. The dish view is now responsive to changes, such as update or delete operations, performed on the source records.

In addition, one small fix was added to the `init.sql` file: the word 'comment' seems to be a reserved keyword in Postgresql, so I replaced it with 'description' in the `restaurant_review` and `reviews_dish` tables.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have updated/created the corresponding documentation

### CODE REVIEW

**Review by AZANK7173 — COMMENTED** [review]
Why is there a Customerview job inside the DishView directory? Is this just a legacy code that should be removed or is it necessary for the DishView?

**Comment by VegSja** [comment]
> Why is there a Customerview job inside the DishView? Is this just a legacy code that should be removed or is it necessary for the DishView?
> 
> EDIT: now that I've seen it, this code is in other branches as well, does anyone knows where it came from?

I am guessing this is because the DishView aggregates data from the restauranttable aswell, and the code has been copied from restaurantview to make things easier. I agree that this sort of stuff should be shared though. I can look into this and create a refactor PR when I have the time this sprint

**Review by VegSja — CHANGES_REQUESTED** [review]
I tried the PR in the docker containers and it does not connect to mongoDB and kafka. I have had this problem before and it is because the mongodb_url and kafka_uri is hardcoded in the view.

By having variables fetch the environment variables like this, it will work:

```java
        private static final String KAFKA_URI = System.getenv("KAFKA_URI");
        private static final String MONGODB_URI = System.getenv("MONGODB_SERVER");
```

I did not get the time to properly test this on my machine though since I am driving (not while writing this ofcourse :wink: )

**Comment by VegSja** [comment]
I tested with the change of 

> I tried the PR in the docker containers and it does not connect to mongoDB and kafka. I have had this problem before and it is because the mongodb_url and kafka_uri is hardcoded in the view.
> 
> By having variables fetch the environment variables like this, it will work:
> 
> ```java
>         private static final String KAFKA_URI = System.getenv("KAFKA_URI");
>         private static final String MONGODB_URI = System.getenv("MONGODB_SERVER");
> ```
> 
> I did not get the time to properly test this on my machine though since I am driving (not while writing this ofcourse 😉 )

## Background
I managed to test this now. At first it did not work using the docker container since the docker container runs the old flink_startup.sh script (which still has "transforms": "unwrap", and not removed like in the change of @francioniniccolo https://github.com/FlinkFood/FlinkFood/blob/feature/FLIN-99-CustomerView-Rebased/flinkfood-demo/CustomerViewJob/customerView.md). 

However, updated the docker container to use this new script of Niccolo. But now we have a new issue.
The other views are expecting the incoming format of kafka messages to be in the format "json", not "debezium-json" as Niccolo's change mandates. This leads me to the following question/follow up

## Question/Follow up
If we are to follow The change purposed in this document: https://github.com/FlinkFood/FlinkFood/blob/feature/FLIN-99-CustomerView-Rebased/flinkfood-demo/CustomerViewJob/customerView.md

We would have to follow this pattern for the other views as well (since this fundamentally changes the messages of the debezium messages which is basicly the input of our program). This is something we need to discuss how to do. Right now I have the impression that the CustomerView and the DishView is going to implement this change, and it seems to work (?)

## Possible solution I thought of right now
Since this is quite a big change, maybe we can merge this into some inbetween branch where we can test and see if everything works and merge this with develop when all seems to be working?

**Comment by lucamozzz** [comment]
> Since this is quite a big change, maybe we can merge this into some inbetween branch where we can test and see if everything works and merge this with develop when all seems to be working?

I agree with this, I think that we should create a new branch where the RestaurantView uses the same approach and see if everything works fine. I can work on the job that aggregates data for the restaurant view but I'll probably need some help to refactor code, merge branches and make the whole thing run smoothly.

**Comment by lucamozzz** [comment]
Done :)

**Comment by VegSja** [comment]
> Done :)

I just created a branch named "refactor/views-to-use-debezium-json". If we change the target branch of this PR I can accept it if that is fine by you Luca. Then we merge restaurant and dish view with this when it is done

**Comment by VegSja** [comment]
Tested the dishview now and it all seems to work with the small changes I did to the hardcoded kafka uri and mongodb uri. One issue I am seeing is that it is spawning alot of jobs in the FlinkUI. I do not know how big of an issue this is though:
bilde

**Comment by VegSja** [comment]
> Tested the dishview now and it all seems to work with the small changes I did to the hardcoded kafka uri and mongodb uri. One issue I am seeing is that it is spawning alot of jobs in the FlinkUI. I do not know how big of an issue this is though: bilde

My fault. Fixed ^

**Review by VegSja — APPROVED** [review]
LGTM

**Pull request merged**
